import { api, type Query } from '@/lib/api'
import type { TicketCountsWire, TicketShareWire, TicketWire } from './tickets.types'
import type { TicketStatus } from './types'

/** Everything the ticket inventory asks of eventa-api (US-TKT-01..06). */

export interface ListTicketsQuery extends Query {
  page?: number
  limit?: number
  status?: TicketStatus
  eventId?: string
  search?: string
}

/** What a tier is created or edited with — only fields the API accepts. */
export interface TicketInput {
  name: string
  isFree: boolean
  priceSatang: number
  total: number
  maxPerOrder?: number
  salesStartAt?: string
  salesEndAt?: string
  /** Sent on edit only: the API refuses a write against a stale read. */
  version?: number
}

export const ticketsApi = {
  /** The cross-event inventory, filtered and paged by the API. */
  list: (query: ListTicketsQuery) => api.list<TicketWire>('/tickets', { query }),

  /** Every status's count for the whole workspace, whichever tab is open. */
  counts: () => api.get<TicketCountsWire>('/tickets/counts'),

  create: (eventId: string, input: TicketInput) =>
    api.post<TicketWire>(`/events/${eventId}/tickets`, input),

  update: (eventId: string, ticketId: string, input: TicketInput) =>
    api.patch<TicketWire>(`/events/${eventId}/tickets/${ticketId}`, input),

  remove: (eventId: string, ticketId: string) =>
    api.delete<void>(`/events/${eventId}/tickets/${ticketId}`),

  pause: (eventId: string, ticketId: string) =>
    api.post<TicketWire>(`/events/${eventId}/tickets/${ticketId}/pause`),

  resume: (eventId: string, ticketId: string) =>
    api.post<TicketWire>(`/events/${eventId}/tickets/${ticketId}/resume`),

  /**
   * The registration link and its QR — generated by the API.
   *
   * Fetched rather than drawn here: a QR is a promise that scanning it reaches
   * the right page, and only the server knows the public URL of a tier.
   */
  share: (eventId: string, ticketId: string) =>
    api.get<TicketShareWire>(`/events/${eventId}/tickets/${ticketId}/share`),
}
