import type { BadgeTone } from '@/components/ui'
import type { TicketStatus } from './types'

/** What the ticket inventory reads off the wire, and what the cards render. */

export interface TicketWire {
  id: string
  eventId: string
  eventName: string
  name: string
  isFree: boolean
  /** VAT-inclusive gross price in satang; 0 when free. */
  priceSatang: number
  vatRate: number
  status: TicketStatus
  sold: number
  /** The allocation. 0 means unlimited — not "none left". */
  total: number
  salesStartAt: string | null
  salesEndAt: string | null
}

/** How many tiers sit in each status, across the whole workspace. */
export type TicketCountsWire = Record<TicketStatus, number>

export interface TicketShareWire {
  ticketId: string
  ticketName: string
  /** Opens registration with this tier preselected. */
  registrationUrl: string
  /** Inline SVG, generated by the API — it encodes `registrationUrl`. */
  qrSvg: string
  qrEncodes: string
  /** False while the event is draft, cancelled or private. */
  isPublished: boolean
  warning: string | null
}

export interface TicketCard {
  id: string
  eventId: string
  name: string
  event: string
  /** `฿1,250`, or `Free` — the badge swaps for a free tier. */
  price: string
  isFree: boolean
  status: TicketStatus
  statusLabel: string
  statusTone: BadgeTone
  statusIcon: string
  /** `640 / 800 sold`, or `640 sold` when the allocation is unlimited. */
  soldLabel: string
  /** Null when unlimited: there is no share of "no limit" to draw. */
  percent: number | null
  iconTint: string
}
